%YAML 1.2
---

#This config file must appreciated by space, must not be TAB.

#log level:(trace, debug, info, warn, err, critical, off)
spdlog:
  level: "trace"
#local IP, local Port, target IP, target Port, drop 1 packet every n packets, n among [1-100], delay(ms)
#do not support TCP
udp:
  - channel: ["10.160.92.222", 1500, "10.160.92.223", 20002, 20, 100]
  - channel: ["10.160.92.222", 1501, "10.160.92.223", 20003, 20, 100]
  - channel: ["10.160.92.222", 1502, "10.160.92.223", 20004, 20, 100]
...
